### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by misaka-10032** [cocos2d/cocos2d-console#163]
This part is "NOT DONE YET", so when can you update? I see bunch of stuff teaching me what to do after that. They are totally useless to me unless I install this "cocos" command. Anybody can help? Many thanks.

**Comment by natural-law** [comment]
Now console is integrated in the cocos2d-x & cocos2d-js. So you can get the `cocos` command when you have the cocos2d-x/cocos2d-js.
The console is in path `tools/cocos2d-console`.
