### ISSUE TITLE
Plugin Path in cocos2d.ini

### ISSUE THREAD

**Issue by martell** [cocos2d/cocos2d-console#184]
Hi @ricardoquesada 

Could you make the plugin directory the same as the others by retrieving it from cocos2d.ini

Currently it is 
line 690
plugins_path = os.path.join(os.path.dirname(**file**), '..', 'plugins')

A distro might want to put these in a share folder :)

**Comment by ricardoquesada** [comment]
sure. I'll fix it in a few hours.

**Comment by ricardoquesada** [comment]
fixed:
https://github.com/cocos2d/cocos2d-console/commit/9d467700fff95e716ae4963bd544b47ec447d4de
