### ISSUE TITLE
`/Applications/Cocos/Cocos2d-x/` is hard coded for `gen-templates` command

### ISSUE THREAD

**Issue by johnvuko** [cocos2d/cocos2d-console#396]
Hi,
I work on MacOS, I have installed cocos2d in a custom folder, not with the installer but from the git.
When I executed `cocos gen-templates` the templates files have `/Applications/Cocos/Cocos2d-x/` inside.
So when I generate a project with something like `cocos new ProjectName -p projectname.com.name -l cpp -t binary` my project doesn't work because the path for the files are not good.

I use cocos2d-x-3.13.1 and Cocos Console 2.1, I don't know very well the project but I see there is an environment variable named `COCOS_X_ROOT` which may be very useful for this.

Thank you

**Comment by natural-law** [comment]
Please don't use option `-t binary` in the command `cocos new`. It's supplied for Cocos Studio. Sorry for the confusion!

**Comment by johnvuko** [comment]
So you have to update your documentation http://cocos2d-x.org/docs/editors_and_tools/cocosCLTool/

And still, it may be very useful and it's a small change in the code.

**Comment by natural-law** [comment]
Thanks for your feedback!
