### ISSUE TITLE
使用--no-native生成的项目无法使用问题

### ISSUE THREAD

**Issue by wulei** [cocos2d/cocos2d-console#401]
### 我用如下命令生成一个测试项目
```
cocos new -l lua --no-native ~/Documents/Hello
```

### 然后cd到目录下使用：
```
cocos run -p osx 
```

### 报错：
```
没有可用的平台。
```

**Comment by natural-law** [comment]
Please don't use the option `--no-native`. Because it's an option supplied for requirement of Cocos Code IDE. As the IDE project is stopped, we will remove the option ASAP. Sorry for the confusion!
