### ISSUE TITLE
Google removed command "android"

### ISSUE THREAD

**Issue by mars3142** [cocos2d/cocos2d-console#404]
I updated today my Android SDK to the latest version and now, the **android** command is gone. Because of this, the compile with the console is no longer possible, I had to remove the two lines after https://github.com/cocos2d/cocos2d-console/blob/v3/plugins/plugin_compile/build_android.py#L182. 

Wouldn't it be better to check, if **android** is available and only if yes, to call the **android update project**?

**Comment by natural-law** [comment]
It's interesting! Which Android SDK version are you using? I will check for the problem. Thanks for your feedback!

**Comment by natural-law** [comment]
Yep, I find the Android SDK tools release note [here](http://tools.android.com/recent/androidsdktoolsrevision2530feb2017). The android command & ant scripts are removed.

Looks like that command `cocos compile` should make these changes:
1. Can't support Eclipse project anymore with Android SDK tools 25.3.0. (Now Eclipse project depends on ant scripts.)
2. Manually write `sdk.dir` to the `local.properties`. (Now it's done by `android update`.)
3. Manually write `target`(API Level) to the `project.properties`. (Now it's done by `android update`.)

**Comment by minggo** [comment]
fixed in https://github.com/cocos2d/cocos2d-console/pull/410
