### ISSUE TITLE
Can't compile static libs with #define CC_USE_PHYSICS 0

### ISSUE THREAD

**Issue by Anywhere-Music-Player** [cocos2d/cocos2d-console#414]
Set:

`#define CC_USE_PHYSICS 0`

And just run ` cocos gen-libs -p mac`

Result:
`../cocos2d/cocos/scripting/lua-bindings/auto/lua_cocos2dx_auto.cpp:11287:18: error: no type named 'PhysicsWorld' in namespace 'cocos2d'; did you mean 'PhysicsBody'?`
And many more such errors for cocos2d::PhysicsBody

** BUILD FAILED **
Error running command, return code: 65.

**Comment by natural-law** [comment]
> #define CC_USE_PHYSICS 0

Hi, could you please tell me how did you do that? Which project(s) have you modified?
Thanks for your feedback!

**Comment by Anywhere-Music-Player** [comment]
Changed here https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/base/ccConfig.h

So, just downloaded cocos from github and tried to build libs.

**Comment by Anywhere-Music-Player** [comment]
Any update? Issue is still there.

**Comment by KAMIKAZEUA** [comment]
Ended this by editing some config file to remove compile of lua- and other not needed for me. Only iOS and android left.
