### ISSUE TITLE
With Xcode 8.3 PackageApplication is gone

### ISSUE THREAD

**Issue by bushimichi** [cocos2d/cocos2d-console#418]
You need change xcrun to xcodebuild.
xcrun -> xcodebuild -exportArchive

-----------------------------------------------------
https://github.com/cocos2d/cocos2d-console/blob/v3/plugins/plugin_compile/project_compile.py
# line 826
            if self._sign_id is not None:
                # generate the ipa
                app_path = os.path.join(output_dir, "%s.app" % targetName)
                ipa_path = os.path.join(output_dir, "%s.ipa" % targetName)
                ipa_cmd = "xcrun -sdk %s PackageApplication -v \"%s\" -o \"%s\"" % (self.use_sdk, app_path, ipa_path)

                self._run_cmd(ipa_cmd)

--------------------------------------------------------

* ref
http://stackoverflow.com/questions/43094380/whats-the-replacement-for-xcodes-packageapplication

**Comment by bushimichi** [comment]
xcodebuild -sdk iphoneos \
  -workspace ${XCWORKSPACE_NAME} -scheme ${SCHEME_NAME} \
  -configuration Release archive \
  -archivePath ${ARCHIVE_PATH} \
  SYMROOT=${BUILD_NUMBER_PATH} \
  CODE_SIGN_IDENTITY="${CODE_SIGN_ID}" \
  PROVISIONING_PROFILE="${PROVISIONING_ID}"

xcodebuild -exportArchive \
  -archivePath "${ARCHIVE_PATH}" \
  -exportPath "${BUILD_NUMBER_PATH}" \
  -exportOptionsPlist "${PLIST_FILE_PATH}"

**Comment by minggo** [comment]
it is fixed
