### ISSUE TITLE
Cannot build prebuilt libraries

### ISSUE THREAD

**Issue by piotrros** [cocos2d/cocos2d-console#420]
**cocos gen-libs -p android --android-studio --app-abi armeabi-v7a**
```
running: '/Users/piotr/Documents/pierdoly/cocos2d-x-3.14/tools/cocos2d-console/bin/cocos compile -s /Users/piotr/Documents/pierdoly/cocos2d-x-3.14/tools/simulator -p android --ndk-mode release --app-abi armeabi-v7a'

Building mode: debug
Using Eclipse project : /Users/piotr/Documents/pierdoly/cocos2d-x-3.14/tools/simulator/frameworks/runtime-src/proj.android
Ant (Eclipse project) is not supported from Android SDK Tools 25.3.0.
Error running command, return code: 101.
```

I've got the latest cocos console and sdk tools. Using cocos2d-x 3.14.1 (if that matters anyway).

**Comment by quannv108** [comment]
This cause because Eclipse project not support (deprecated) by Google, you should use android studio instead

**Comment by Anywhere-Music-Player** [comment]
@kudo108 how should I use android studio to generate libs?

**Comment by piotrros** [comment]
I've added  --android-studio switch and output are the same:

**cocos gen-libs -p android --android-studio --app-abi armeabi-v7a --ap android-26**

```
running: '/Users/piotr/Documents/pierdoly/cocos2d-x/tools/cocos2d-console/bin/cocos compile -s /Users/piotr/Documents/pierdoly/cocos2d-x/tools/simulator -p android --ndk-mode release --app-abi armeabi-v7a --ap android-26'

Building mode: debug
Using Eclipse project : /Users/piotr/Documents/pierdoly/cocos2d-x/tools/simulator/frameworks/runtime-src/proj.android
Ant (Eclipse project) is not supported from Android SDK Tools 25.3.0.
Error running command, return code: 101.
```

Looks like it's ignoring --android-studio parameter.
There's not even such a parameter listed in cocos gen-libs -h:

```
usage: cocos gen-libs [-h] [-c] [-e ENGINE_PATH] [-p {ios,mac,android,win32}]
                      [-m {debug,release}] [--dis-strip] [--vs VS_VERSION]
                      [--app-abi APP_ABI] [--ap ANDROID_PLATFORM]

Generate prebuilt libs of engine. The libs will be placed in 'prebuilt' folder
of the engine root path.

optional arguments:
  -h, --help            show this help message and exit
  -c                    Remove the 'prebuilt' folder at first.
  -e ENGINE_PATH        Specify the engine path. Default is the engine root
                        path of current tools.
  -p {ios,mac,android,win32}
                        Specify the target platform. Can specify multi
                        platform by using '-p' multi times. Default generate
                        all available platforms.
  -m {debug,release}, --mode {debug,release}
                        Generate cocos libs for debug or release. Default is
                        release.
  --dis-strip           Disable the strip of the generated libs.

Windows Options:
  --vs VS_VERSION       Specify the Visual Studio version, such as 2013.
                        Default find available version automatically.

Android Options:
  --app-abi APP_ABI     Set the APP_ABI of ndk-build. Can be multi value
                        separated with ':'. Sample : --app-abi
                        armeabi:x86:mips. Default value is 'armeabi'.
  --ap ANDROID_PLATFORM
                        Specify the Android platform used for building Android
                        apk.
```

So, how?

**Comment by quannv108** [comment]
@piotrros  I found solutions I made on my laptops. Sorry, I made it before but I don't remember it so I can't response soon.
- Download Android SDK tools before version 25.0.0 then replace it to your ANDROID_SDK/tools folder
(or just download my folder here: https://drive.google.com/open?id=0B7cCirG2ZzPOUDlHb29QNmxGaTg)
- run your command again
Hope this can help!

**Comment by piotrros** [comment]
Thanks, but this is hack, isn't it? It's just using old build tools.

**Comment by Anywhere-Music-Player** [comment]
Yes, that hack and as I understand there is no other way. However, with NDK 14+ it's not working http://discuss.cocos2d-x.org/t/pre-built-libs-for-android-not-compiles-with-ndk-14/38923/2?u=kamikaze

I've tested on 14 and 15, but only 13 works ok with hack. So probably cocos2d-x should be updated to latest NDK?  Because it's like legacy: 
`Cocos2d-x/cocos/./2d/CCActionGrid3D.cpp:509: error: undefined reference to 'rand’`
@minggo  ?

**Comment by minggo** [comment]
@piotrros i think it is because `cocos gen-libs` doesn't adapt to use gradle, so you should copy old tools folder from older Android SDK.

**Comment by piotrros** [comment]
I get the solution, but couldn't you update gen-libs to use gradle?

**Comment by minggo** [comment]
yep, sure.

**Comment by Anywhere-Music-Player** [comment]
@minggo that would be cool, but any time estimations?

**Comment by minggo** [comment]
Espect to fix it after v3.16.

**Comment by Anywhere-Music-Player** [comment]
@minggo really looking forward for this :)

**Comment by piotrros** [comment]
Not only you ;)

**Comment by Anywhere-Music-Player** [comment]
@minggo  Any progress? It's really can be done? Can I use all latest SDK and tools with something like:
`cocos gen-libs -p android --android-studio --app-abi armeabi-v7a --ap android-19` ?

**Comment by Anywhere-Music-Player** [comment]
@piotrros do you think it will be fixed someday :) ? It;s already android studio 3.0 arrive and maybe with it we got new problems?

**Comment by piotrros** [comment]
Maybe in 3.17, what do you think @minggo?

**Comment by Anywhere-Music-Player** [comment]
@piotrros I've actually abandoned using of prebuilts for android,  source code always works... so I'm suggesting to drop it. And seeing how cocos2d-x currently supported by developers - like no support at all, so be sure to use source code option, as something much more stable, because someday you anyway will switch to it.

**Comment by piotrros** [comment]
Actually, I've just checked the latest version (3.17) from github, which will be soon released and... No need for old built tools works with ndk r16 (and probably r17, but haven't checked that yet). So it's definitely a good sing.

**Comment by Anywhere-Music-Player** [comment]
Release date for 3.17 was many times changed. 3.16 was reported as very unstable and with some strange crashed. Do you really think they testing it? I'm not thinking to use it for production games. How actually it's tested.. any information? Maybe some production games using it and got no bugs? Well, I'm stick with older version anyway..

**Comment by minggo** [comment]
3.17 is testing, will be released in this month.

**Comment by kienvn** [comment]
Did any one build prebuilt in 3.17?

**Comment by quannv108** [comment]
> Did any one build prebuilt in 3.17?

yes, it still worked. you can try upgrade cocos-console to newest version

**Comment by kienvn** [comment]
> > Did any one build prebuilt in 3.17?
> 
> yes, it still worked. you can try upgrade cocos-console to newest version

I try 3.17.1 it say:
```
Error: argument 'gen-libs -p android -m release' not found.
Try with cocos -h
```

**Comment by piotrros** [comment]
Show the full command. It should work :)

**Comment by kienvn** [comment]
yeah, it worked like a charm!

**Comment by piotrros** [comment]
I don't know how, but I'm glad I helped :)
