### ISSUE TITLE
Can not compile ios after update XCode 8.3.2

### ISSUE THREAD

**Issue by quannv108** [cocos2d/cocos2d-console#422]
Before update, every thing is ok
After update Xcode 8.3.2, then update cocos2d-console to newest
but now I got problem:
invalid literal for float(): 8.3.2
please check.

**Comment by 1scaR1** [comment]
Problem is in plugins/plugin_compile/project_compile.py file on line ~810
`use_new_ipa_method = float(cocos.get_xcode_version()) >= 8.3`
